import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import vue from 'eslint-plugin-vue';
import vueParser from 'vue-eslint-parser';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

// Generated by unplugin-auto-import on dev/build and tracked in git so a
// fresh clone lints cleanly. Contains the list of names (ref, computed,
// defineStore, ...) that the plugin injects as globals so they no longer
// need explicit imports.
let autoImportGlobals = {};
try {
  const filepath = fileURLToPath(
    new URL('./apps/client/.eslintrc-auto-import.json', import.meta.url),
  );
  const parsed = JSON.parse(readFileSync(filepath, 'utf8'));
  autoImportGlobals = parsed.globals ?? {};
} catch {
  // File missing — regenerate by running `pnpm --filter @tarkov-checker/client dev`
  // once. Until then auto-import names will be flagged as no-undef.
}

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/.turbo/**',
      '**/coverage/**',
      'apps/desktop/src-tauri/target/**',
      'apps/desktop/src-tauri/gen/**',
      'apps/client/dev-dist/**',
      '**/.vite/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...vue.configs['flat/recommended'],
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.node, ...globals.browser, ...autoImportGlobals },
    },
    rules: {
      'no-console': 'warn',
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    files: ['**/*.vue'],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        parser: tseslint.parser,
        ecmaVersion: 2022,
        sourceType: 'module',
        extraFileExtensions: ['.vue'],
      },
    },
    rules: {
      'vue/multi-word-component-names': 'off',
    },
  },
  {
    // Hybrid import style in the client: same-feature stays relative (./X,
    // ../store), cross-feature MUST go through the @/ alias. The two-or-more
    // levels-up pattern is the load-bearing signal — it's how you'd reach
    // out of the current feature, and that should be explicit.
    files: ['apps/client/src/**/*.{ts,vue}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['../../*', '../../**/*', '../../../*', '../../../**/*'],
              message:
                'Cross-feature/cross-layer import — use @/features/<name>/... or @/shared/... instead.',
            },
          ],
        },
      ],
    },
  },
  prettier,
);
