import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import vue from "eslint-plugin-vue";
import vueParser from "vue-eslint-parser";
import prettier from "eslint-config-prettier";
import globals from "globals";

// Generated by unplugin-auto-import on dev/build. Contains the list of names
// (ref, computed, defineStore, ...) that the plugin injects as globals so
// they no longer need explicit imports. Missing on a fresh clone before the
// first vite run — empty globals object is a safe fallback.
let autoImportGlobals = {};
try {
  const filepath = fileURLToPath(
    new URL("./apps/client/.eslintrc-auto-import.json", import.meta.url),
  );
  const parsed = JSON.parse(readFileSync(filepath, "utf8"));
  autoImportGlobals = parsed.globals ?? {};
} catch {
  // First run before vite has generated the file; auto-import names will be
  // flagged as no-undef until then. Run `pnpm dev` once.
}

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      "**/.turbo/**",
      "**/coverage/**",
      "apps/desktop/src-tauri/target/**",
      "apps/desktop/src-tauri/gen/**",
      "apps/client/dev-dist/**",
      "**/.vite/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...vue.configs["flat/recommended"],
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.node, ...globals.browser, ...autoImportGlobals },
    },
    rules: {
      "no-console": "warn",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  {
    files: ["**/*.vue"],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        parser: tseslint.parser,
        ecmaVersion: 2022,
        sourceType: "module",
        extraFileExtensions: [".vue"],
      },
    },
    rules: {
      "vue/multi-word-component-names": "off",
    },
  },
  prettier,
);
