//! Watches the Tarkov screenshots folder and parses player position out
//! of each new filename. Parsing helpers ultimately come from
//! `packages/shared/src/parse-screenshot.ts`. Regex pattern
//! strings live in the auto-generated `parse_screenshot_regexes` module
//! (generated by `pnpm shared:gen-rust-regex` from the TS source).

use anyhow::{Context, Result};
use notify::{EventKind, RecursiveMode, Watcher};
use notify_debouncer_full::{new_debouncer, DebouncedEvent, Debouncer, FileIdMap};
use once_cell::sync::Lazy;
use regex::Regex;
use serde::Serialize;
use std::path::{Path, PathBuf};
use std::sync::mpsc;
use std::time::Duration;
use tauri::{AppHandle, Emitter};

use super::parse_screenshot_regexes;

// Patterns sourced from the auto-generated parse_screenshot_regexes module.
// Edit packages/shared/src/parse-screenshot.ts and run `pnpm shared:gen-rust-regex`
// to update; do not hand-edit the pattern strings here.
static POSITION_RE: Lazy<Regex> =
    Lazy::new(|| Regex::new(parse_screenshot_regexes::POSITION_RE_STR).expect("static regex"));
static ORIENTATION_RE: Lazy<Regex> =
    Lazy::new(|| Regex::new(parse_screenshot_regexes::ORIENTATION_RE_STR).expect("static regex"));

#[derive(Debug, Clone, Copy)]
pub struct Position3d {
    pub x: f64,
    pub y: f64,
    pub z: f64,
}

#[derive(Debug, Clone, Copy)]
pub struct Quaternion {
    pub qx: f64,
    pub qy: f64,
    pub qz: f64,
    pub qw: f64,
}

#[derive(Debug, Clone, Copy)]
pub struct ParsedScreenshot {
    pub position: Position3d,
    pub orientation: Option<Quaternion>,
}

fn basename(p: &Path) -> Option<&str> {
    p.file_name().and_then(|n| n.to_str())
}

/// Parse the Tarkov PrintScreen-overlay screenshot filename. See the TS original
/// for the format reference.
pub fn parse_screenshot_filename(path: &Path) -> Option<ParsedScreenshot> {
    let base = basename(path)?;
    if !base.to_ascii_lowercase().ends_with(".png") {
        return None;
    }
    let pos = POSITION_RE.captures(base)?;
    let x = pos.get(1)?.as_str().parse::<f64>().ok()?;
    let y = pos.get(2)?.as_str().parse::<f64>().ok()?;
    let z = pos.get(3)?.as_str().parse::<f64>().ok()?;
    if ![x, y, z].iter().all(|v| v.is_finite()) {
        return None;
    }

    let orientation = ORIENTATION_RE.captures(base).and_then(|m| {
        let qx = m.get(4)?.as_str().parse::<f64>().ok()?;
        let qy = m.get(5)?.as_str().parse::<f64>().ok()?;
        let qz = m.get(6)?.as_str().parse::<f64>().ok()?;
        let qw = m.get(7)?.as_str().parse::<f64>().ok()?;
        if [qx, qy, qz, qw].iter().all(|v| v.is_finite()) {
            Some(Quaternion { qx, qy, qz, qw })
        } else {
            None
        }
    });

    Some(ParsedScreenshot {
        position: Position3d { x, y, z },
        orientation,
    })
}

/// Yaw in degrees from a Tarkov orientation quaternion. Direct port of
/// `quaternionToYawDegrees` in TS; see that doc-comment for axis convention.
pub fn quaternion_to_yaw_degrees(q: Quaternion) -> f64 {
    let sin_yaw = 2.0 * (q.qw * q.qy + q.qz * q.qx);
    let cos_yaw = 1.0 - 2.0 * (q.qx * q.qx + q.qy * q.qy);
    sin_yaw.atan2(cos_yaw).to_degrees()
}

#[derive(Debug, Clone, Serialize)]
struct PositionPayload {
    t: i64,
    x: f64,
    y: f64,
    z: f64,
    yaw: Option<f64>,
}

/// Owns the notify debouncer + the reader thread. Drop = stop.
pub struct ScreenshotWatcher {
    // Hold the debouncer alive; dropping it stops the underlying watcher.
    _debouncer: Debouncer<notify::RecommendedWatcher, FileIdMap>,
}

/// Start watching `dir` non-recursively. New .png files matching the
/// PrintScreen-overlay pattern emit a `position` event on the AppHandle
/// AND on the broadcast channel feeding the HTTP `/events` stream.
///
/// chokidar's `awaitWriteFinish: { stabilityThreshold: 250 }` is mirrored
/// here by the debouncer's 250 ms timeout — only events that have been
/// quiet for the whole window are reported.
pub fn start(
    dir: PathBuf,
    app: AppHandle,
    event_tx: tokio::sync::broadcast::Sender<crate::server::events::ServerEvent>,
) -> Result<ScreenshotWatcher> {
    let (tx, rx) = mpsc::channel::<notify_debouncer_full::DebounceEventResult>();
    let mut debouncer =
        new_debouncer(Duration::from_millis(250), None, tx).context("create fs debouncer")?;
    debouncer
        .watcher()
        .watch(&dir, RecursiveMode::NonRecursive)
        .with_context(|| format!("watch {}", dir.display()))?;
    // notify-debouncer-full's FileIdMap caches inode-style ids; tell it to
    // stop tracking the parent so we don't grow it unboundedly over a
    // long session.
    debouncer
        .cache()
        .add_root(&dir, RecursiveMode::NonRecursive);

    // Reader thread — exits when the sender side of `rx` is dropped along
    // with the debouncer.
    let app_handle = app.clone();
    std::thread::Builder::new()
        .name("screenshot-watcher".into())
        .spawn(move || {
            for batch in rx {
                let events = match batch {
                    Ok(ev) => ev,
                    Err(_) => continue,
                };
                for ev in events {
                    handle_event(&app_handle, &event_tx, ev);
                }
            }
        })
        .context("spawn watcher thread")?;

    Ok(ScreenshotWatcher {
        _debouncer: debouncer,
    })
}

fn handle_event(
    app: &AppHandle,
    event_tx: &tokio::sync::broadcast::Sender<crate::server::events::ServerEvent>,
    ev: DebouncedEvent,
) {
    // Only fresh-on-disk files matter — chokidar in TS used the `add`
    // event which fires on initial discovery + new creates. notify's
    // `Create` covers the same case; we also accept `Modify(Name(Any))`
    // for atomic renames some screenshot tools use.
    let interesting = matches!(
        ev.kind,
        EventKind::Create(_) | EventKind::Modify(notify::event::ModifyKind::Name(_))
    );
    if !interesting {
        return;
    }
    for path in &ev.paths {
        let Some(parsed) = parse_screenshot_filename(path) else {
            continue;
        };
        let yaw = parsed.orientation.map(quaternion_to_yaw_degrees);
        let t = chrono_now_ms();
        // Tauri webview path — unchanged. Uses the private PositionPayload
        // struct so the webview's existing `listen("position", ...)` keeps
        // working bit-for-bit.
        let payload = PositionPayload {
            t,
            x: parsed.position.x,
            y: parsed.position.y,
            z: parsed.position.z,
            yaw,
        };
        if let Err(err) = app.emit("position", &payload) {
            eprintln!("[screenshot-watcher] emit failed: {err}");
        }
        // HTTP /events path — same data, ServerEvent wire-shape (tagged
        // enum). `send` errors only when there are zero subscribers; that
        // is the normal case when nobody has opened /events, so we ignore
        // it silently.
        let _ = event_tx.send(crate::server::events::ServerEvent::Position {
            t,
            x: parsed.position.x,
            y: parsed.position.y,
            z: parsed.position.z,
            yaw,
        });
    }
}

fn chrono_now_ms() -> i64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    // -----------------------------------------------------------------------
    // parse_screenshot_filename
    // -----------------------------------------------------------------------

    // Full filename with position triple then quaternion quadruple — the real
    // BSG PrintScreen-overlay format: date_x,y,z_qx,qy,qz,qw_.png
    //
    // `clippy::approx_constant` flags `0.7071` as an approximation of
    // `FRAC_1_SQRT_2` and suggests using the constant directly. Here it's
    // intentional — the literal in the filename's quaternion field IS
    // `0.7071` (truncated to 4 decimals by BSG's screenshot tool), so the
    // assertion checks parsing of that exact string, not a math identity.
    #[test]
    #[allow(clippy::approx_constant)]
    fn parse_screenshot_filename_full_with_orientation() {
        // ORIENTATION_RE: _x,y,z_qx,qy,qz,qw_
        // POSITION_RE:    _x,y,z_
        // Both anchors are underscores, so the pattern is _3nums_4nums_.
        let path =
            Path::new("2026-05-30 12-34-56_-100.5, 50.0, 200.3_0.0, 0.0, 0.7071, 0.7071_.png");
        let result = parse_screenshot_filename(path);
        assert!(result.is_some(), "expected Some, got None");
        let parsed = result.unwrap();
        // Position values come from POSITION_RE groups 1-3.
        assert_eq!(parsed.position.x, -100.5);
        assert_eq!(parsed.position.y, 50.0);
        assert_eq!(parsed.position.z, 200.3);
        // Orientation must be present (ORIENTATION_RE matched groups 4-7).
        assert!(parsed.orientation.is_some());
        let q = parsed.orientation.unwrap();
        assert_eq!(q.qx, 0.0);
        assert_eq!(q.qy, 0.0);
        assert!((q.qz - 0.7071).abs() < 1e-4);
        assert!((q.qw - 0.7071).abs() < 1e-4);
    }

    // Filename with only position, no quaternion suffix.
    #[test]
    fn parse_screenshot_filename_position_only_no_orientation() {
        // A filename with position triple but no second number-group after it.
        let path = Path::new("screenshot_10.5, -20.0, 300.0_.png");
        let result = parse_screenshot_filename(path);
        assert!(result.is_some(), "expected Some for position-only filename");
        let parsed = result.unwrap();
        assert_eq!(parsed.position.x, 10.5);
        assert_eq!(parsed.position.y, -20.0);
        assert_eq!(parsed.position.z, 300.0);
        // No orientation because only one numeric group present.
        assert!(
            parsed.orientation.is_none(),
            "expected no orientation for position-only filename"
        );
    }

    // Non-PNG extension must return None.
    #[test]
    fn parse_screenshot_filename_jpg_extension_returns_none() {
        let path = Path::new("2026-05-30 12-34-56_10.0, 20.0, 30.0_.jpg");
        assert!(parse_screenshot_filename(path).is_none());
    }

    // Completely unrelated filename returns None.
    #[test]
    fn parse_screenshot_filename_plain_name_returns_none() {
        let path = Path::new("screenshot.png");
        assert!(parse_screenshot_filename(path).is_none());
    }

    // Path with backslash directory prefix — basename must be stripped.
    #[test]
    fn parse_screenshot_filename_backslash_path_uses_basename() {
        let path = Path::new("D:\\Screenshots\\2026-05-30 12-00-00_5.0, 6.0, 7.0_.png");
        let result = parse_screenshot_filename(path);
        assert!(
            result.is_some(),
            "backslash path should resolve basename correctly"
        );
        let parsed = result.unwrap();
        assert_eq!(parsed.position.x, 5.0);
        assert_eq!(parsed.position.y, 6.0);
        assert_eq!(parsed.position.z, 7.0);
    }

    // -----------------------------------------------------------------------
    // quaternion_to_yaw_degrees — four cardinal orientations
    // -----------------------------------------------------------------------

    // Identity quaternion (0, 0, 0, 1) → 0 degrees.
    #[test]
    fn quaternion_to_yaw_degrees_identity_is_zero() {
        let q = Quaternion {
            qx: 0.0,
            qy: 0.0,
            qz: 0.0,
            qw: 1.0,
        };
        let yaw = quaternion_to_yaw_degrees(q);
        assert!(
            (yaw - 0.0).abs() < 1e-6,
            "identity quaternion must give 0°, got {yaw}"
        );
    }

    // 90° yaw around Y axis (looking left): qy = sin(45°) ≈ 0.7071, qw = cos(45°) ≈ 0.7071.
    #[test]
    fn quaternion_to_yaw_degrees_90_degrees() {
        let half = std::f64::consts::FRAC_PI_4; // 45° in radians
        let q = Quaternion {
            qx: 0.0,
            qy: half.sin(),
            qz: 0.0,
            qw: half.cos(),
        };
        let yaw = quaternion_to_yaw_degrees(q);
        assert!((yaw - 90.0).abs() < 1e-4, "expected ~90°, got {yaw}");
    }

    // 180° yaw: qy = 1, qw = 0.
    #[test]
    fn quaternion_to_yaw_degrees_180_degrees() {
        let q = Quaternion {
            qx: 0.0,
            qy: 1.0,
            qz: 0.0,
            qw: 0.0,
        };
        let yaw = quaternion_to_yaw_degrees(q);
        assert!(
            (yaw.abs() - 180.0).abs() < 1e-4,
            "expected ±180°, got {yaw}"
        );
    }

    // 270° yaw (or -90°): qy = -sin(45°), qw = cos(45°).
    #[test]
    fn quaternion_to_yaw_degrees_270_degrees() {
        let half = std::f64::consts::FRAC_PI_4;
        let q = Quaternion {
            qx: 0.0,
            qy: -(half.sin()),
            qz: 0.0,
            qw: half.cos(),
        };
        let yaw = quaternion_to_yaw_degrees(q);
        assert!((yaw - (-90.0)).abs() < 1e-4, "expected ~-90°, got {yaw}");
    }
}
