/**
 * Bearer-token storage for the LAN-phone / hosted-page scenarios.
 *
 * The token is generated by the Rust helper (Windows Credential Manager
 * backing store) and reaches the browser via the QR-pairing flow (D4):
 * the SPA's bootstrap reads `window.location.hash` on first load, copies
 * `#token=…` into `localStorage`, and clears the URL fragment.
 *
 * The Tauri webview NEVER reads this — it talks to the helper via IPC,
 * which has its own trust boundary. Only the in-browser code path
 * (transport.ts fetch + useServerStream EventSource) reaches in here.
 *
 * In LAN-off mode the helper does not enforce the bearer, so a missing
 * token is harmless. The header / query string is just appended when
 * present — frontend doesn't need to know whether the helper is in LAN
 * mode or not.
 */

const STORAGE_KEY = 'tc.auth.token';

export function getAuthToken(): string | null {
  try {
    return localStorage.getItem(STORAGE_KEY);
  } catch {
    // localStorage can throw on private-browsing / quota-exceeded /
    // disabled-storage cases. Treat any failure as "no token" — the
    // helper will respond 401 if it actually needs one, and the
    // pairing flow will then prompt the user.
    return null;
  }
}

export function setAuthToken(token: string): void {
  try {
    localStorage.setItem(STORAGE_KEY, token);
  } catch {
    // Silent. The user will need to re-pair every session if storage
    // is unavailable — acceptable for the edge case.
  }
}

export function clearAuthToken(): void {
  try {
    localStorage.removeItem(STORAGE_KEY);
  } catch {
    // Same rationale as setAuthToken — best effort.
  }
}
